/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zc_study_Multi1JNI */

#ifndef _Included_com_zc_study_Multi1JNI
#define _Included_com_zc_study_Multi1JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zc_study_Multi1JNI
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zc_study_Multi1JNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
